version: '3.8'
services:
  bachhoasi-api:
    container_name: bachhoasi-api-management
    image: ${DOCKER_USERNAME}/bach-hoa-si-api:latest
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      DB_URL: postgresql-bachhoasi
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      PENV: ${PENV}
      PORT: ${PORT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      ACCESS_TOKEN_EXT: ${ACCESS_TOKEN_EXT}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      REFRESH_TOKEN_EXT: ${REFRESH_TOKEN_EXT}
      BASE_URL_API: ${BASE_URL_API}
      ORIGIN_ALLOWED: ${ORIGIN_ALLOWED}
      BUCKET: ${BUCKET}
      GG_CREDENTIAL_JSON: ${GG_CREDENTIAL_JSON}
    networks:
      - bachhoasi-networks

networks:
  bachhoasi-networks:
    name: bachhoasi-networks
    external: true
