version: '3.8'
services:
  postgresql-bachhoasi:
    container_name: postgresql-bachhoasi-database
    image: postgres:13.14-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - bachhoasi-networks

  pg-admin-rode:
    container_name: postgres-admin-local
    image: elestio/pgadmin:REL-8_6
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGA_PORT}
    networks:
      - bachhoasi-networks
    ports:
      - ${PGA_PORT}:${PGA_PORT}

  bachhoasi-api:
    container_name: bachhoasi-api-management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      DB_URL: postgresql-bachhoasi
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_DATABASE}
      PENV: ${PENV}
      AWS_ACCESS_ID: ${AWS_ACCESS_ID}
      BUCKET_NAME: ${BUCKET_NAME} 
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      PORT: ${PORT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      ACCESS_TOKEN_EXT: ${ACCESS_TOKEN_EXT}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      REFRESH_TOKEN_EXT: ${REFRESH_TOKEN_EXT}
      BASE_URL_API: ${BASE_URL_API}
      ORIGIN_ALLOWED: ${ORIGIN_ALLOWED}
    networks:
      - bachhoasi-networks

networks:
  bachhoasi-networks:
