version: '3.8'
services:
  postgresql-bachhoasi:
    container_name: postgresql-bachhoasi-database
    image: postgres:13.14-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - bachhoasi-networks
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  bachhoasi-api:
    container_name: bachhoasi-api-management
    image: ${DOCKER_USERNAME}/bach-hoa-si-api:latest
    ports:
      - ${PORT}:${PORT}
    restart: always
    environment:
      DB_URL: postgresql-bachhoasi
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      PENV: ${PENV}
      PORT: ${PORT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      ACCESS_TOKEN_EXT: ${ACCESS_TOKEN_EXT}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      REFRESH_TOKEN_EXT: ${REFRESH_TOKEN_EXT}
      BASE_URL_API: ${BASE_URL_API}
      ORIGIN_ALLOWED: ${ORIGIN_ALLOWED}
      BUCKET: ${BUCKET}
      GG_CREDENTIAL_PATH: /bachhoasi
      GG_CREDENTIAL_NAME: ${GG_CREDENTIAL_NAME}
    volumes:
      - ${GG_LOCAL_CREDENTIAL_PATH}/${GG_CREDENTIAL_NAME}:/bachhoasi/${GG_CREDENTIAL_NAME}
    networks:
      - bachhoasi-networks

networks:
  bachhoasi-networks:

volumes:
  postgres-data:
  pgadmin-data: