on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  bach-hoa-si-api-build:
    name: Build source code to Docker image
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build API image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/bach-hoa-si-api:latest .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/bach-hoa-si-api:latest

      - name: Run registry garbage collection
        run: doctl registry garbage-collection start --include-untagged-manifests --force
  
  staging-api-deploy:
    name: Deploy Staging API Manager To Google Service Server For Testing
    runs-on: deploy
    needs: bach-hoa-si-api-build
    env:
      PGA_EMAIL: ${{secrets.PGA_EMAIL}}
      PGA_PASSWORD: ${{secrets.PGA_PASSWORD}}
      PGA_PORT: ${{secrets.PGA_PORT}}

      DB_PORT: ${{secrets.DB_PORT}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_NAME: ${{secrets.DB_NAME}}

      PENV: staging

      ACCESS_TOKEN_KEY: ${{secrets.ACCESS_TOKEN_KEY}}
      ACCESS_TOKEN_EXT: ${{secrets.ACCESS_TOKEN_EXT}}
      REFRESH_TOKEN_KEY: ${{secrets.REFRESH_TOKEN_KEY}}
      REFRESH_TOKEN_EXT: ${{secrets.REFRESH_TOKEN_EXT}}

      PORT: ${{secrets.PORT}}
      BASE_URL_API: ${{secrets.BASE_URL_API}}
      ORIGIN_ALLOWED: ${{secrets.ORIGIN_ALLOWED}}
      GG_LOCAL_CREDENTIAL_PATH: ${{secrets.GG_CREDENTIAL_PATH}}
      GG_CREDENTIAL_NAME: ${{secrets.GG_CREDENTIAL_NAME}}
      BUCKET: ${{secrets.BUCKET}}

      DOCKER_USERNAME: ${{ secrets.REGISTRY_NAME }}
    steps:
    - name: Checkout Develop
      uses: actions/checkout@v3

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Stop BachHoaSi API
      run: docker compose -f docker-compose.test.yaml -p bach-hoa-si-api down bachhoasi-api

    - name: Clean Old BachHoaSi Image
      run: docker rmi ${{ secrets.REGISTRY_NAME }}/bach-hoa-si-api:latest 
      continue-on-error: true

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Deploy API
      run: docker compose -f docker-compose.test.yaml -p bach-hoa-si-api up -d bachhoasi-api