on:
  push:
    branches: ["main"]

jobs:
  bach-hoa-si-api-build:
    name: Build source code to Docker image
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: DockerHub Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Image And Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/bach-hoa-si-api:latest
  
  staging-api-deploy:
    name: Deploy Staging API Manager To Google Service Server For Testing
    runs-on: deploy
    needs: bach-hoa-si-api-build
    env:
      PGA_EMAIL: ${{secrets.PGA_EMAIL}}
      PGA_PASSWORD: ${{secrets.PGA_PASSWORD}}
      PGA_PORT: ${{secrets.PGA_PORT}}

      DB_PORT: ${{secrets.DB_PORT}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_NAME: ${{secrets.DB_NAME}}

      PENV: staging

      ACCESS_TOKEN_KEY: ${{secrets.ACCESS_TOKEN_KEY}}
      ACCESS_TOKEN_EXT: ${{secrets.ACCESS_TOKEN_EXT}}
      REFRESH_TOKEN_KEY: ${{secrets.REFRESH_TOKEN_KEY}}
      REFRESH_TOKEN_EXT: ${{secrets.REFRESH_TOKEN_EXT}}

      PORT: ${{secrets.PORT}}
      BASE_URL_API: ${{secrets.BASE_URL_API}}
      ORIGIN_ALLOWED: ${{secrets.ORIGIN_ALLOWED}}

      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    steps:
    - name: Checkout Develop
      uses: actions/checkout@v3
    - name: DockerHub Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Stop BachHoaSi API
      run: docker compose -f docker-compose.test.yaml -p bach-hoa-si-api-test down bachhoasi-api
    - name: Clean Old BachHoaSi Image
      run: docker rmi ${{secrets.DOCKER_USERNAME}}/bach-hoa-si-api:latest 
    - name: Deploy API
      run: docker compose -f docker-compose.test.yaml -p bach-hoa-si-api-test up -d bachhoasi-api